Fix invalid param value "use_gpu":"true"
Fix invalid param value "use_gpu":"true", due to passing a string value

instead of a boolean value for a parameter in a Jupyter Notebook Python code.

```
params = {
    "tree_method": "gpu_hist",
    "grow_policy": "depthwise",
    "num_workers": 1,
    "use_gpu": "true",
}
```
TypeError: Invalid param value given for param "use_gpu".

Boolean Param requires value of type bool. Found <class 'str'>.

Signed-off-by: Tim Liu <timl@nvidia.com>